name: commitlint
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    permissions:
      pull-requests: write
    uses: liara-engine/.github/.github/workflows/reusable-commitlint.yml@v0

  manifest-validation:
    permissions:
      contents: read
      pull-requests: write
    uses: liara-engine/.github/.github/workflows/reusable-validate-manifest.yml@v0
    with:
      package: '.'
