name: preview-cleanup
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    uses: liara-engine/.github/.github/workflows/reusable-docs-preview-cleanup.yml@v0
    with:
      output-repository: liara-engine/liara-docs
    secrets:
      push-token: ${{ secrets.DOCS_PUSH_TOKEN }}
