name: release-please
on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ORG_RELEASE_PLEASE_TOKEN }}
