name: release-please
on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      pull-requests: write

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.ORG_RELEASE_PLEASE_TOKEN }}

  artifact-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    uses: liara-engine/.github/.github/workflows/reusable-release-artifacts.yml@v2
    with:
      module: liara-renderer
      version: ${{ needs.release-please.outputs.version }}
      tag_name: ${{ needs.release-please.outputs.tag_name }}
      github-repo-version: v2
